# Generated by Django 2.2.16 on 2020-10-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_gfghfhgfhgfgh"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="ghfhgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hfhgfhf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
