# Generated by Django 2.2.16 on 2020-10-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20201007_1148"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext",
            old_name="gfghfhgfhgfgh",
            new_name="hgfhg",
        ),
        migrations.RemoveField(
            model_name="customtext",
            name="ghfhgf",
        ),
        migrations.AlterField(
            model_name="customtext",
            name="title",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
