# Generated by Django 2.2.16 on 2020-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201007_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hgfhhggj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgfhgfghfhgfhgf', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
